import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    paddingTop: 10,
    paddingRight: 20,
    paddingLeft: 20,
    alighnItems: "center",
    backgroundColor: "#f5f5f5",
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  imageContainer: {
    width: "100%",
    height: "auto",
    overflow: "hidden",
  },
  profileImage: {
    marginTop: 10,
    marginBottom: 10,
    width: 350,
    height: 250,
    borderWidth: 0.2,
  },
  nameContainer: {
    flexDirection: "row",
    alignItems: "left",
    marginVertical: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: "#fff",
    borderBottomRightRadius:20,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  contactContainer: {
    height: "auto",
    alignItems: "left",
    marginVertical: 10,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: "#fff",
    borderBottomRightRadius:20,
    elevation: 2,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  subtitle: {
    textAlign: "left",
    fontWeight: "bold",
    fontSize: 18,
    marginBottom: 10,
  },
  name: {
    fontSize: 20,
    textAlign: "left",
    fontWeight: "500",
    color: "#333",
    fontWeight: "bold",
  },
  role : {
    textAlignHorizantal: "center",
    marginLeft: "50%",
    fontSize: 16,
    color: "green",
  },
  input: {
    width: "100%",
    height: 45,
    fontSize: 18,
    marginBottom: 10,
    borderColor: "#FF7043",
    borderWidth: 1,
    fontStyle: "italic",
    borderColor: "transparent",
    paddingLeft: 10,
    borderRadius: 20,
    backgroundColor: "#fffff",
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginTop: 10,
  },
  inputEditable: {
    borderColor: "#FF7043", 
  },

  editButton: {
    backgroundColor: "#FF7043",
    paddingVertical: 12,
    borderRadius: 8,
    flex: 1,
    alignItems: "center",
    marginRight: 5,
  },
  saveButton: {
    backgroundColor: "#FF7043",
    paddingVertical: 12,
    borderRadius: 5,
    flex: 1,
    alignItems: "center",
    marginRight: 5,
  },
  cancelButton: {
    backgroundColor: "#fff",
    paddingVertical: 12,
    borderRadius: 5,
    borderColor: "#FF7043",
    borderWidth: 1,
    flex: 1,
    alignItems: "center",
  },
  cancelbuttonText: {
    color: "#FF7043",
    fontSize: 16,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
  },
});
export default styles;